/* eslint-disable import/prefer-default-export */
// User
export const ADD_USER_TO_STATE = 'ADD_USER_TO_STATE'
export const UPDATE_USER = 'UPDATE_USER'
export const SIGNUP_SIGNIN_FAILURE = 'SIGNUP_SIGNIN_FAILURE'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
export const GET_USER_INTERESTS = 'GET_USER_INTERESTS'
export const ADD_USER_INTERESTS = 'ADD_USER_INTERESTS'

// Interest
export const GET_INTERESTS = 'GET_INTERESTS'

// Channels
export const GET_CHANNEL_INVITATIONS = 'GET_CHANNEL_INVITATIONS'

// Mattermost
export const STORE_REHYDRATION_FAILED = 'STORE_REHYDRATION_FAILED'
